"""Add reports and blocks

Revision ID: f3661e46d35d
Revises: 9250825bd5ee
Create Date: 2026-05-11 02:22:11.630103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3661e46d35d'
down_revision = '9250825bd5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='unique_block')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index('idx_block_blocked', ['blocked_id'], unique=False)
        batch_op.create_index('idx_block_blocker', ['blocker_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'reported_id', name='unique_report')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_report_reported', ['reported_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index('idx_report_reported')

    op.drop_table('reports')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index('idx_block_blocker')
        batch_op.drop_index('idx_block_blocked')

    op.drop_table('blocks')
    # ### end Alembic commands ###
